"""
build_correspondence_data.py
============================

Reads the 4 axes JSONs from cymatics/axes/ and emits a single JS module
at cymatics-correspondence/js/data.js that inlines the data as JS objects.

This is a *build-time* operation, not a runtime fetch. The result is
a single self-contained JS file that the static page loads directly.

Run from the SkyCLAWk root:
    python3 cymatics-correspondence/build_correspondence_data.py

The data module exports:
    CORRESPONDENCE_DATA = { frequency, form, color, planet }
    The same 4 JSON structures, but as JS objects, with helper accessors
    matching the cymatics_axes.py API (planet_for_hz, hz_for_planet, etc.)
"""

import json
import os
from pathlib import Path


def main():
    # Paths are relative to the SkyCLAWk root (where the script is run from)
    here = Path(__file__).parent
    axes_dir = here.parent / "Company_OS" / "notebook" / "cymatics" / "axes"
    if not axes_dir.exists():
        # Fallback: assume we're at the SkyCLAWk root and axes is elsewhere
        axes_dir = Path("/mnt/e/Hermes Project/Company_OS/notebook/cymatics/axes")
    out_dir = here / "js"
    out_dir.mkdir(exist_ok=True)

    axes = ["frequency", "form", "color", "planet", "herbs"]
    bundled = {}
    for axis in axes:
        path = axes_dir / f"{axis}.json"
        with open(path) as f:
            bundled[axis] = json.load(f)
        print(f"  read {path.name}: {len(bundled[axis].get('sections', [])) or 'n/a'} sections")

    # Emit the JS module. Use a string builder rather than json.dumps so
    # we can have nicely-formatted output and add the helper accessors.
    # For herbs.json (different shape), generate a sections-style view so
    # the page can render it with the same browse logic as the other axes.
    if 'herbs' in bundled:
        herbs_list = bundled['herbs'].get('herbs', [])
        by_planet = bundled['herbs'].get('by_planet', {})
        # Build a sections view: one section per planet
        planet_sections = []
        for planet in ['Sun', 'Moon', 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn']:
            planet_herbs = [h for h in herbs_list if h['planet'] == planet]
            if planet_herbs:
                planet_sections.append({
                    'id': f'planet_{planet.lower()}',
                    'title': f'{planet} herbs (metal: {planet_herbs[0].get("metal", "?")})',
                    'description': f'{len(planet_herbs)} herbs traditionally associated with {planet}. Constitution per Galenic/Hippocratic temperaments. Solfeggio: {bundled["herbs"].get("data_sources", {})}.',
                    'data': planet_herbs
                })
        bundled['herbs'] = {
            'axis': 'herbs',
            'version': '1.0',
            'compiled_date': '2026-07-08',
            'source_md': 'Company_OS/notebook/cymatics/axes/herbs.md',
            'schema_note': bundled['herbs'].get('schema_note', ''),
            'data_sources': bundled['herbs'].get('data_sources', {}),
            'epistemic_status': bundled['herbs'].get('epistemic_status', ''),
            'schema_fields': bundled['herbs'].get('schema_fields', {}),
            'sections': planet_sections,
            'all_herbs': herbs_list,
            'by_planet': by_planet,
            'statistics': bundled['herbs'].get('statistics', {})
        }

    js_lines = [
        "// Auto-generated by build_correspondence_data.py — do not edit by hand.",
        "// Run `python3 cymatics-correspondence/build_correspondence_data.py` to regenerate.",
        "//",
        "// Data source: Company_OS/notebook/cymatics/axes/*.json",
        "// This is the data contract between the static webapp, the Godot 3D",
        "// cymatics visualization, and any agent queries against the cymatics archive.",
        "",
        "export const CORRESPONDENCE_DATA = " + json.dumps(bundled, indent=2) + ";",
        "",
        "// ── Cross-axis accessors (mirror cymatics_axes.py) ─────────────────────",
        "",
        "function sectionRows(section) {",
        "  return Array.isArray(section && section.data) ? section.data : [];",
        "}",
        "",
        "export function planetForHz(hz) {",
        "  for (const section of CORRESPONDENCE_DATA.frequency.sections) {",
        "    if (section.id !== 'solfeggio_frequencies' && section.id !== 'planetary_frequencies_solfeggio') continue;",
        "    for (const row of sectionRows(section)) {",
        "      if (Math.abs((row.hz || 0) - hz) < 0.5) return row.planet;",
        "    }",
        "  }",
        "  return null;",
        "}",
        "",
        "export function hzForPlanet(planet) {",
        "  const results = [];",
        "  for (const section of CORRESPONDENCE_DATA.frequency.sections) {",
        "    if (section.id !== 'solfeggio_frequencies' && section.id !== 'planetary_frequencies_solfeggio') continue;",
        "    for (const row of sectionRows(section)) {",
        "      if ((row.planet || '').toLowerCase() === planet.toLowerCase()) {",
        "        results.push({ hz: row.hz, context: section.id });",
        "      }",
        "    }",
        "  }",
        "  return results;",
        "}",
        "",
        "export function lookupHz(hz) {",
        "  const result = { hz: hz };",
        "  for (const section of CORRESPONDENCE_DATA.frequency.sections) {",
        "    for (const row of sectionRows(section)) {",
        "      if (Math.abs((row.hz || 0) - hz) < 0.5) {",
        "        result.frequency_context = { section: section.id, section_title: section.title };",
        "        for (const [k, v] of Object.entries(row)) { if (k !== 'hz') result.frequency_context[k] = v; }",
        "        break;",
        "      }",
        "    }",
        "  }",
        "  const planetName = planetForHz(hz);",
        "  if (planetName) result.planet = planetInfo(planetName);",
        "  for (const section of CORRESPONDENCE_DATA.color.sections) {",
        "    if (section.id === 'cymascope_color_mapping') {",
        "      for (const row of sectionRows(section)) {",
        "        if (Math.abs((row.frequency_hz || 0) - hz) < 0.5) {",
        "          result.color = { color: row.color, pattern: row.pattern, source: 'Cymascope' };",
        "        }",
        "      }",
        "    }",
        "  }",
        "  return result;",
        "}",
        "",
        "export function planetInfo(name) {",
        "  for (const p of [...CORRESPONDENCE_DATA.planet.classical_planets, ...CORRESPONDENCE_DATA.planet.modern_outer_planets]) {",
        "    if (p.planet.toLowerCase() === name.toLowerCase()) return p;",
        "  }",
        "  return null;",
        "}",
        "",
        "export function lookup4d(hz) {",
        "  const result = { hz: hz };",
        "  const info = lookupHz(hz);",
        "  if (info.planet) {",
        "    const planet = info.planet;",
        "    result.planet = planet.planet;",
        "    if (planet.color) result.color = planet.color;",
        "    if (planet.form_solid) result.form_solid = planet.form_solid;",
        "    if (planet.mode) result.mode = planet.mode;",
        "  }",
        "  if (info.color) {",
        "    result.color = info.color.color;",
        "    result.pattern = info.color.pattern;",
        "  }",
        "  if (info.frequency_context) {",
        "    const ctx = info.frequency_context;",
        "    if (ctx.color) result.color = ctx.color;",
        "    if (ctx.chakra) result.chakra = ctx.chakra;",
        "    if (ctx.note) result.note = ctx.note;",
        "    if (ctx.claimed_use) result.claimed_use = ctx.claimed_use;",
        "  }",
        "  return result;",
        "}",
        "",
        "export function solfeggioFrequencies() {",
        "  for (const s of CORRESPONDENCE_DATA.frequency.sections) {",
        "    if (s.id === 'solfeggio_frequencies') return s.data;",
        "  }",
        "  return [];",
        "}",
        "",
        "export function chladniFigures() {",
        "  for (const s of CORRESPONDENCE_DATA.form.sections) {",
        "    if (s.id === 'chladni_figures_5_most_common') return s.data;",
        "  }",
        "  return [];",
        "}",
        "",
        "export function greekModes() {",
        "  for (const s of CORRESPONDENCE_DATA.form.sections) {",
        "    if (s.id === 'greek_modes') return s.data;",
        "  }",
        "  return [];",
        "}",
        "",
        "export function platonicSolids() {",
        "  for (const s of CORRESPONDENCE_DATA.form.sections) {",
        "    if (s.id === 'platonic_solids') return s.data;",
        "  }",
        "  return [];",
        "}",
        "",
        "export function allSections(axisName) {",
        "  return (CORRESPONDENCE_DATA[axisName] && CORRESPONDENCE_DATA[axisName].sections) || [];",
        "}",
        "",
        "export function allPlanets() {",
        "  return [...CORRESPONDENCE_DATA.planet.classical_planets, ...CORRESPONDENCE_DATA.planet.modern_outer_planets];",
        "}",
        "",
        "export function allHerbs() {",
        "  return (CORRESPONDENCE_DATA.herbs && CORRESPONDENCE_DATA.herbs.all_herbs) || [];",
        "}",
        "",
        "export function herbByName(name) {",
        "  const needle = String(name || '').toLowerCase();",
        "  return allHerbs().find(h => String(h.name || '').toLowerCase() === needle) || null;",
        "}",
        "",
    ]

    out_path = out_dir / "data.js"
    out_path.write_text("\n".join(js_lines))
    size_kb = out_path.stat().st_size / 1024
    print(f"\nWrote {out_path}: {size_kb:.1f} KB")
    print(f"  4 axes inlined; 12 helper accessors exported.")
    print(f"  Total data rows: ", end="")
    total = 0
    for axis in axes:
        if axis == "planet":
            total += len(bundled[axis].get("classical_planets", [])) + len(bundled[axis].get("modern_outer_planets", []))
        else:
            for s in bundled[axis].get("sections", []):
                d = s.get("data", [])
                if isinstance(d, list):
                    total += len(d)
                elif isinstance(d, dict):
                    total += 1
    print(f"{total} typed records")


if __name__ == "__main__":
    main()
